class CountryTimezone {
  final String name;
  final String code; // 2-letter ISO country code (lowercase) for flag CDN
  final String timezone; // Default IANA timezone name

  const CountryTimezone({
    required this.name,
    required this.code,
    required this.timezone,
  });
}

const List<CountryTimezone> countryTimezones = [
  CountryTimezone(name: 'Afghanistan', code: 'af', timezone: 'Asia/Kabul'),
  CountryTimezone(name: 'Albania', code: 'al', timezone: 'Europe/Tirane'),
  CountryTimezone(name: 'Algeria', code: 'dz', timezone: 'Africa/Algiers'),
  CountryTimezone(name: 'Andorra', code: 'ad', timezone: 'Europe/Andorra'),
  CountryTimezone(name: 'Angola', code: 'ao', timezone: 'Africa/Luanda'),
  CountryTimezone(name: 'Argentina', code: 'ar', timezone: 'America/Argentina/Buenos_Aires'),
  CountryTimezone(name: 'Armenia', code: 'am', timezone: 'Asia/Yerevan'),
  CountryTimezone(name: 'Australia', code: 'au', timezone: 'Australia/Sydney'),
  CountryTimezone(name: 'Austria', code: 'at', timezone: 'Europe/Vienna'),
  CountryTimezone(name: 'Azerbaijan', code: 'az', timezone: 'Asia/Baku'),
  CountryTimezone(name: 'Bahamas', code: 'bs', timezone: 'America/Nassau'),
  CountryTimezone(name: 'Bahrain', code: 'bh', timezone: 'Asia/Bahrain'),
  CountryTimezone(name: 'Bangladesh', code: 'bd', timezone: 'Asia/Dhaka'),
  CountryTimezone(name: 'Barbados', code: 'bb', timezone: 'America/Barbados'),
  CountryTimezone(name: 'Belarus', code: 'by', timezone: 'Europe/Minsk'),
  CountryTimezone(name: 'Belgium', code: 'be', timezone: 'Europe/Brussels'),
  CountryTimezone(name: 'Belize', code: 'bz', timezone: 'America/Belize'),
  CountryTimezone(name: 'Benin', code: 'bj', timezone: 'Africa/Porto-Novo'),
  CountryTimezone(name: 'Bhutan', code: 'bt', timezone: 'Asia/Thimphu'),
  CountryTimezone(name: 'Bolivia', code: 'bo', timezone: 'America/La_Paz'),
  CountryTimezone(name: 'Bosnia and Herzegovina', code: 'ba', timezone: 'Europe/Sarajevo'),
  CountryTimezone(name: 'Botswana', code: 'bw', timezone: 'Africa/Gaborone'),
  CountryTimezone(name: 'Brazil', code: 'br', timezone: 'America/Sao_Paulo'),
  CountryTimezone(name: 'Brunei', code: 'bn', timezone: 'Asia/Brunei'),
  CountryTimezone(name: 'Bulgaria', code: 'bg', timezone: 'Europe/Sofia'),
  CountryTimezone(name: 'Burkina Faso', code: 'bf', timezone: 'Africa/Ouagadougou'),
  CountryTimezone(name: 'Burundi', code: 'bi', timezone: 'Africa/Bujumbura'),
  CountryTimezone(name: 'Cambodia', code: 'kh', timezone: 'Asia/Phnom_Penh'),
  CountryTimezone(name: 'Cameroon', code: 'cm', timezone: 'Africa/Douala'),
  CountryTimezone(name: 'Canada', code: 'ca', timezone: 'America/Toronto'),
  CountryTimezone(name: 'Cape Verde', code: 'cv', timezone: 'Atlantic/Cape_Verde'),
  CountryTimezone(name: 'Central African Republic', code: 'cf', timezone: 'Africa/Bangui'),
  CountryTimezone(name: 'Chad', code: 'td', timezone: 'Africa/Ndjamena'),
  CountryTimezone(name: 'Chile', code: 'cl', timezone: 'America/Santiago'),
  CountryTimezone(name: 'China', code: 'cn', timezone: 'Asia/Shanghai'),
  CountryTimezone(name: 'Colombia', code: 'co', timezone: 'America/Bogota'),
  CountryTimezone(name: 'Comoros', code: 'km', timezone: 'Indian/Comoro'),
  CountryTimezone(name: 'Congo', code: 'cg', timezone: 'Africa/Brazzaville'),
  CountryTimezone(name: 'Costa Rica', code: 'cr', timezone: 'America/Costa_Rica'),
  CountryTimezone(name: 'Croatia', code: 'hr', timezone: 'Europe/Zagreb'),
  CountryTimezone(name: 'Cuba', code: 'cu', timezone: 'America/Havana'),
  CountryTimezone(name: 'Cyprus', code: 'cy', timezone: 'Asia/Nicosia'),
  CountryTimezone(name: 'Czech Republic', code: 'cz', timezone: 'Europe/Prague'),
  CountryTimezone(name: 'Denmark', code: 'dk', timezone: 'Europe/Copenhagen'),
  CountryTimezone(name: 'Djibouti', code: 'dj', timezone: 'Africa/Djibouti'),
  CountryTimezone(name: 'Dominica', code: 'dm', timezone: 'America/Dominica'),
  CountryTimezone(name: 'Dominican Republic', code: 'do', timezone: 'America/Santo_Domingo'),
  CountryTimezone(name: 'Ecuador', code: 'ec', timezone: 'America/Guayaquil'),
  CountryTimezone(name: 'Egypt', code: 'eg', timezone: 'Africa/Cairo'),
  CountryTimezone(name: 'El Salvador', code: 'sv', timezone: 'America/El_Salvador'),
  CountryTimezone(name: 'Equatorial Guinea', code: 'gq', timezone: 'Africa/Malabo'),
  CountryTimezone(name: 'Eritrea', code: 'er', timezone: 'Africa/Asmara'),
  CountryTimezone(name: 'Estonia', code: 'ee', timezone: 'Europe/Tallinn'),
  CountryTimezone(name: 'Eswatini', code: 'sz', timezone: 'Africa/Mbabane'),
  CountryTimezone(name: 'Ethiopia', code: 'et', timezone: 'Africa/Addis_Ababa'),
  CountryTimezone(name: 'Fiji', code: 'fj', timezone: 'Pacific/Fiji'),
  CountryTimezone(name: 'Finland', code: 'fi', timezone: 'Europe/Helsinki'),
  CountryTimezone(name: 'France', code: 'fr', timezone: 'Europe/Paris'),
  CountryTimezone(name: 'Gabon', code: 'ga', timezone: 'Africa/Libreville'),
  CountryTimezone(name: 'Gambia', code: 'gm', timezone: 'Africa/Banjul'),
  CountryTimezone(name: 'Georgia', code: 'ge', timezone: 'Asia/Tbilisi'),
  CountryTimezone(name: 'Germany', code: 'de', timezone: 'Europe/Berlin'),
  CountryTimezone(name: 'Ghana', code: 'gh', timezone: 'Africa/Accra'),
  CountryTimezone(name: 'Greece', code: 'gr', timezone: 'Europe/Athens'),
  CountryTimezone(name: 'Grenada', code: 'gd', timezone: 'America/Grenada'),
  CountryTimezone(name: 'Guatemala', code: 'gt', timezone: 'America/Guatemala'),
  CountryTimezone(name: 'Guinea', code: 'gn', timezone: 'Africa/Conakry'),
  CountryTimezone(name: 'Guinea-Bissau', code: 'gw', timezone: 'Africa/Bissau'),
  CountryTimezone(name: 'Guyana', code: 'gy', timezone: 'America/Guyana'),
  CountryTimezone(name: 'Haiti', code: 'ht', timezone: 'America/Port-au-Prince'),
  CountryTimezone(name: 'Honduras', code: 'hn', timezone: 'America/Tegucigalpa'),
  CountryTimezone(name: 'Hungary', code: 'hu', timezone: 'Europe/Budapest'),
  CountryTimezone(name: 'Iceland', code: 'is', timezone: 'Atlantic/Reykjavik'),
  CountryTimezone(name: 'India', code: 'in', timezone: 'Asia/Kolkata'),
  CountryTimezone(name: 'Indonesia', code: 'id', timezone: 'Asia/Jakarta'),
  CountryTimezone(name: 'Iran', code: 'ir', timezone: 'Asia/Tehran'),
  CountryTimezone(name: 'Iraq', code: 'iq', timezone: 'Asia/Baghdad'),
  CountryTimezone(name: 'Ireland', code: 'ie', timezone: 'Europe/Dublin'),
  CountryTimezone(name: 'Israel', code: 'il', timezone: 'Asia/Jerusalem'),
  CountryTimezone(name: 'Italy', code: 'it', timezone: 'Europe/Rome'),
  CountryTimezone(name: 'Jamaica', code: 'jm', timezone: 'America/Jamaica'),
  CountryTimezone(name: 'Japan', code: 'jp', timezone: 'Asia/Tokyo'),
  CountryTimezone(name: 'Jordan', code: 'jo', timezone: 'Asia/Amman'),
  CountryTimezone(name: 'Kazakhstan', code: 'kz', timezone: 'Asia/Almaty'),
  CountryTimezone(name: 'Kenya', code: 'ke', timezone: 'Africa/Nairobi'),
  CountryTimezone(name: 'Kiribati', code: 'ki', timezone: 'Pacific/Tarawa'),
  CountryTimezone(name: 'Kosovo', code: 'xk', timezone: 'Europe/Belgrade'),
  CountryTimezone(name: 'Kuwait', code: 'kw', timezone: 'Asia/Kuwait'),
  CountryTimezone(name: 'Kyrgyzstan', code: 'kg', timezone: 'Asia/Bishkek'),
  CountryTimezone(name: 'Laos', code: 'la', timezone: 'Asia/Vientiane'),
  CountryTimezone(name: 'Latvia', code: 'lv', timezone: 'Europe/Riga'),
  CountryTimezone(name: 'Lebanon', code: 'lb', timezone: 'Asia/Beirut'),
  CountryTimezone(name: 'Lesotho', code: 'ls', timezone: 'Africa/Maseru'),
  CountryTimezone(name: 'Liberia', code: 'lr', timezone: 'Africa/Monrovia'),
  CountryTimezone(name: 'Libya', code: 'ly', timezone: 'Africa/Tripoli'),
  CountryTimezone(name: 'Liechtenstein', code: 'li', timezone: 'Europe/Vaduz'),
  CountryTimezone(name: 'Lithuania', code: 'lt', timezone: 'Europe/Vilnius'),
  CountryTimezone(name: 'Luxembourg', code: 'lu', timezone: 'Europe/Luxembourg'),
  CountryTimezone(name: 'Madagascar', code: 'mg', timezone: 'Indian/Antananarivo'),
  CountryTimezone(name: 'Malawi', code: 'mw', timezone: 'Africa/Blantyre'),
  CountryTimezone(name: 'Malaysia', code: 'my', timezone: 'Asia/Kuala_Lumpur'),
  CountryTimezone(name: 'Maldives', code: 'mv', timezone: 'Indian/Maldives'),
  CountryTimezone(name: 'Mali', code: 'ml', timezone: 'Africa/Bamako'),
  CountryTimezone(name: 'Malta', code: 'mt', timezone: 'Europe/Valetta'),
  CountryTimezone(name: 'Marshall Islands', code: 'mh', timezone: 'Pacific/Majuro'),
  CountryTimezone(name: 'Mauritania', code: 'mr', timezone: 'Africa/Nouakchott'),
  CountryTimezone(name: 'Mauritius', code: 'mu', timezone: 'Indian/Mauritius'),
  CountryTimezone(name: 'Mexico', code: 'mx', timezone: 'America/Mexico_City'),
  CountryTimezone(name: 'Micronesia', code: 'fm', timezone: 'Pacific/Chuuk'),
  CountryTimezone(name: 'Moldova', code: 'md', timezone: 'Europe/Chisinau'),
  CountryTimezone(name: 'Monaco', code: 'mc', timezone: 'Europe/Monaco'),
  CountryTimezone(name: 'Mongolia', code: 'mn', timezone: 'Asia/Ulaanbaatar'),
  CountryTimezone(name: 'Montenegro', code: 'me', timezone: 'Europe/Podgorica'),
  CountryTimezone(name: 'Morocco', code: 'ma', timezone: 'Africa/Casablanca'),
  CountryTimezone(name: 'Mozambique', code: 'mz', timezone: 'Africa/Maputo'),
  CountryTimezone(name: 'Myanmar', code: 'mm', timezone: 'Asia/Yangon'),
  CountryTimezone(name: 'Namibia', code: 'na', timezone: 'Africa/Windhoek'),
  CountryTimezone(name: 'Nauru', code: 'nr', timezone: 'Pacific/Nauru'),
  CountryTimezone(name: 'Nepal', code: 'np', timezone: 'Asia/Kathmandu'),
  CountryTimezone(name: 'Netherlands', code: 'nl', timezone: 'Europe/Amsterdam'),
  CountryTimezone(name: 'New Zealand', code: 'nz', timezone: 'Pacific/Auckland'),
  CountryTimezone(name: 'Nicaragua', code: 'ni', timezone: 'America/Managua'),
  CountryTimezone(name: 'Niger', code: 'ne', timezone: 'Africa/Niamey'),
  CountryTimezone(name: 'Nigeria', code: 'ng', timezone: 'Africa/Lagos'),
  CountryTimezone(name: 'North Korea', code: 'kp', timezone: 'Asia/Pyongyang'),
  CountryTimezone(name: 'North Macedonia', code: 'mk', timezone: 'Europe/Skopje'),
  CountryTimezone(name: 'Norway', code: 'no', timezone: 'Europe/Oslo'),
  CountryTimezone(name: 'Oman', code: 'om', timezone: 'Asia/Muscat'),
  CountryTimezone(name: 'Pakistan', code: 'pk', timezone: 'Asia/Karachi'),
  CountryTimezone(name: 'Palau', code: 'pw', timezone: 'Pacific/Palau'),
  CountryTimezone(name: 'Palestine', code: 'ps', timezone: 'Asia/Hebron'),
  CountryTimezone(name: 'Panama', code: 'pa', timezone: 'America/Panama'),
  CountryTimezone(name: 'Papua New Guinea', code: 'pg', timezone: 'Pacific/Port_Moresby'),
  CountryTimezone(name: 'Paraguay', code: 'py', timezone: 'America/Asuncion'),
  CountryTimezone(name: 'Peru', code: 'pe', timezone: 'America/Lima'),
  CountryTimezone(name: 'Philippines', code: 'ph', timezone: 'Asia/Manila'),
  CountryTimezone(name: 'Poland', code: 'pl', timezone: 'Europe/Warsaw'),
  CountryTimezone(name: 'Portugal', code: 'pt', timezone: 'Europe/Lisbon'),
  CountryTimezone(name: 'Qatar', code: 'qa', timezone: 'Asia/Qatar'),
  CountryTimezone(name: 'Romania', code: 'ro', timezone: 'Europe/Bucharest'),
  CountryTimezone(name: 'Russia', code: 'ru', timezone: 'Europe/Moscow'),
  CountryTimezone(name: 'Rwanda', code: 'rw', timezone: 'Africa/Kigali'),
  CountryTimezone(name: 'Saint Kitts and Nevis', code: 'kn', timezone: 'America/St_Kitts'),
  CountryTimezone(name: 'Saint Lucia', code: 'lc', timezone: 'America/St_Lucia'),
  CountryTimezone(name: 'Saint Vincent and the Grenadines', code: 'vc', timezone: 'America/St_Vincent'),
  CountryTimezone(name: 'Samoa', code: 'ws', timezone: 'Pacific/Apia'),
  CountryTimezone(name: 'San Marino', code: 'sm', timezone: 'Europe/San_Marino'),
  CountryTimezone(name: 'Sao Tome and Principe', code: 'st', timezone: 'Africa/Sao_Tome'),
  CountryTimezone(name: 'Saudi Arabia', code: 'sa', timezone: 'Asia/Riyadh'),
  CountryTimezone(name: 'Senegal', code: 'sn', timezone: 'Africa/Dakar'),
  CountryTimezone(name: 'Serbia', code: 'rs', timezone: 'Europe/Belgrade'),
  CountryTimezone(name: 'Seychelles', code: 'sc', timezone: 'Indian/Mahe'),
  CountryTimezone(name: 'Sierra Leone', code: 'sl', timezone: 'Africa/Freetown'),
  CountryTimezone(name: 'Singapore', code: 'sg', timezone: 'Asia/Singapore'),
  CountryTimezone(name: 'Slovakia', code: 'sk', timezone: 'Europe/Bratislava'),
  CountryTimezone(name: 'Slovenia', code: 'si', timezone: 'Europe/Ljubljana'),
  CountryTimezone(name: 'Solomon Islands', code: 'sb', timezone: 'Pacific/Guadalcanal'),
  CountryTimezone(name: 'Somalia', code: 'so', timezone: 'Africa/Mogadishu'),
  CountryTimezone(name: 'South Africa', code: 'za', timezone: 'Africa/Johannesburg'),
  CountryTimezone(name: 'South Korea', code: 'kr', timezone: 'Asia/Seoul'),
  CountryTimezone(name: 'South Sudan', code: 'ss', timezone: 'Africa/Juba'),
  CountryTimezone(name: 'Spain', code: 'es', timezone: 'Europe/Madrid'),
  CountryTimezone(name: 'Sri Lanka', code: 'lk', timezone: 'Asia/Colombo'),
  CountryTimezone(name: 'Sudan', code: 'sd', timezone: 'Africa/Khartoum'),
  CountryTimezone(name: 'Suriname', code: 'sr', timezone: 'America/Paramaribo'),
  CountryTimezone(name: 'Sweden', code: 'se', timezone: 'Europe/Stockholm'),
  CountryTimezone(name: 'Switzerland', code: 'ch', timezone: 'Europe/Zurich'),
  CountryTimezone(name: 'Syria', code: 'sy', timezone: 'Asia/Damascus'),
  CountryTimezone(name: 'Taiwan', code: 'tw', timezone: 'Asia/Taipei'),
  CountryTimezone(name: 'Tajikistan', code: 'tj', timezone: 'Asia/Dushanbe'),
  CountryTimezone(name: 'Tanzania', code: 'tz', timezone: 'Africa/Dar_es_Salaam'),
  CountryTimezone(name: 'Thailand', code: 'th', timezone: 'Asia/Bangkok'),
  CountryTimezone(name: 'Timor-Leste', code: 'tl', timezone: 'Asia/Dili'),
  CountryTimezone(name: 'Togo', code: 'tg', timezone: 'Africa/Lome'),
  CountryTimezone(name: 'Tonga', code: 'to', timezone: 'Pacific/Tongatapu'),
  CountryTimezone(name: 'Trinidad and Tobago', code: 'tt', timezone: 'America/Port_of_Spain'),
  CountryTimezone(name: 'Tunisia', code: 'tn', timezone: 'Africa/Tunis'),
  CountryTimezone(name: 'Turkey', code: 'tr', timezone: 'Europe/Istanbul'),
  CountryTimezone(name: 'Turkmenistan', code: 'tm', timezone: 'Asia/Ashgabat'),
  CountryTimezone(name: 'Tuvalu', code: 'tv', timezone: 'Pacific/Funafuti'),
  CountryTimezone(name: 'Uganda', code: 'ug', timezone: 'Africa/Kampala'),
  CountryTimezone(name: 'Ukraine', code: 'ua', timezone: 'Europe/Kyiv'),
  CountryTimezone(name: 'United Arab Emirates', code: 'ae', timezone: 'Asia/Dubai'),
  CountryTimezone(name: 'United Kingdom', code: 'gb', timezone: 'Europe/London'),
  CountryTimezone(name: 'United States', code: 'us', timezone: 'America/New_York'),
  CountryTimezone(name: 'Uruguay', code: 'uy', timezone: 'America/Montevideo'),
  CountryTimezone(name: 'Uzbekistan', code: 'uz', timezone: 'Asia/Tashkent'),
  CountryTimezone(name: 'Vanuatu', code: 'vu', timezone: 'Pacific/Efate'),
  CountryTimezone(name: 'Vatican City', code: 'va', timezone: 'Europe/Vatican'),
  CountryTimezone(name: 'Venezuela', code: 've', timezone: 'America/Caracas'),
  CountryTimezone(name: 'Vietnam', code: 'vn', timezone: 'Asia/Ho_Chi_Minh'),
  CountryTimezone(name: 'Yemen', code: 'ye', timezone: 'Asia/Aden'),
  CountryTimezone(name: 'Zambia', code: 'zm', timezone: 'Africa/Lusaka'),
  CountryTimezone(name: 'Zimbabwe', code: 'zw', timezone: 'Africa/Harare'),
];
